name: riverpod_state_notifier_provider
description: "A StateNotifier Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  # data modeler( freezed generate )
  freezed: ^2.4.5
  # json_serializable: ^6.7.1
  # riverpod generator
  # riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
